### ISSUE TITLE
incorrect padding

### ISSUE THREAD

**Issue by stopczyk** [mdiez/pyCZDS#2]
Hi,

You should fix padding also in _get_token_jwt_payload in authentication.py

```
  File "/usr/local/lib/python3.10/dist-packages/pyczds/client.py", line 26, in _do_request
    if not self._is_authenticated():
  File "/usr/local/lib/python3.10/dist-packages/pyczds/authentication.py", line 44, in _is_authenticated
    j = self._get_token_jwt_payload()
  File "/usr/local/lib/python3.10/dist-packages/pyczds/authentication.py", line 33, in _get_token_jwt_payload
    s = base64.b64decode(payload_b64)
  File "/usr/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

```

after I change it to
```
s = base64.b64decode(payload_b64 + '=' * (-len(payload_b64) % 4))
```

it works flawlessly

**Comment by mdiez** [comment]
Thank you Marcin for reporting this! Can you create a pull request? Regards, Max

**Comment by raylin2023** [comment]
Does this resolve, I also got this  Incorrect padding error, please help.

---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
[<ipython-input-69-7d685b2ac096>](https://localhost:8080/#) in <cell line: 1>()
----> 1 print(c.get_zonefiles_list())
      2 # # [
      3 #     'https://czds-download-api.icann.org/czds/downloads/net.zone',
      4 #     ...
      5 #     'https://czds-download-api.icann.org/czds/downloads/com.zone'

4 frames
[/usr/lib/python3.10/base64.py](https://localhost:8080/#) in b64decode(s, altchars, validate)
     85     if validate and not re.fullmatch(b'[A-Za-z0-9+/]*={0,2}', s):
     86         raise binascii.Error('Non-base64 digit found')
---> 87     return binascii.a2b_base64(s)
     88 
     89 

Error: Incorrect padding

**Comment by mdiez** [comment]
@tiagom101 created a pull request that solves this problem. Thanks again @raylin2023 for reporting this issue!
